name: Continuous Integration
on:
  push:
    tags:
      - "*"
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

jobs:
  build-pdfs:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.actor }}/${{ github.repository }}:main
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Builds the latest pdf
        run: |
          git config --global --add safe.directory /__w/${{ github.actor}/${{ github.repository }}
          make src/metadata.tex
          make wqo-on-words.pdf
      - name: Builds the zip archive
        run: |
          make wqo-on-words.arxiv.tar.gz
          make wqo-on-words.arxiv.pdf
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wqo-on-words.pdf
          path: wqo-on-words.pdf
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wqo-on-words.arxiv.pdf
          path: wqo-on-words.arxiv.pdf
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wqo-on-words.arxiv.tar.gz
          path: wqo-on-words.arxiv.tar.gz

