name: CI

on:
  push:
    branches:
      - main

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y stow pandoc
      - name: Setup compilation environment
        run: |
          make setup-lipics
          make setup-lncs
      - name: Generate lipics tex file
        run: make wqo-on-words.lipics.tex
      - name: Compile Latex Document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: |
            wqo-on-words.tex
            wqo-on-words.lncs.tex
            wqo-on-words.lipics.tex
      - name: Upload PDFs
        uses: actions/upload-artifact@v4
        with:
          name: pdfs
          path: |
            wqo-on-words.pdf
            wqo-on-words.lncs.pdf
            wqo-on-words.lipics.pdf
